### ISSUE TITLE
Running testdev on node 6.9.0 on OSX fails 

### ISSUE THREAD

**Issue by szydan** [sirensolutions/kibi_timeline_vis#119]
```
gulp testdev --kibanahomepath=../kibi-internal
[23:50:41] Using gulpfile ~/home/workspace-kibana/kibi-timeline-plugin/gulpfile.js
[23:50:41] Starting 'sync'...
building file list ... done

sent 84 bytes  received 20 bytes  208.00 bytes/sec
total size is 1043  speedup is 10.03
building file list ... done

sent 80 bytes  received 20 bytes  200.00 bytes/sec
total size is 248  speedup is 2.48
building file list ... done

sent 764 bytes  received 20 bytes  1568.00 bytes/sec
total size is 89342  speedup is 113.96
[23:50:41] Finished 'sync' after 753 ms
[23:50:41] Starting 'testdev'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn grunt ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by szydan** [comment]
Installing grunt and grunt-cli globally fixed the problem

**Comment by rendel** [comment]
Btw, there is a task in the gradle script that install grunt globally for you:
https://github.com/sirensolutions/kibi-enterprise/blob/master/kibi-plugins/build.gradle#L178

In fact the gradle script for the kibi-enterprise plugin is setting up the environment for you (and for being able to run the test, etc.).
