### ISSUE TITLE
Compatibility with Kibana 4.5

### ISSUE THREAD

**Issue by pittoch** [sirensolutions/kibi_timeline_vis#22]
Hi,

How can we install your plugin on Kibana 4.5 ?

With Kibana 4.5 I have this error:
```
[root@sources]# ../kibana/bin/kibana plugin -i kibi_timeline_vis  -u file:///data/ELK/sources/kibi_timeline_vis-master.zip
Installing kibi_timeline_vis
Attempting to transfer from file:///data/ELK/sources/kibi_timeline_vis-master.zip
Transferring 6340638 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in ../kibana-4.5.0-linux-x64/installedPlugins/kibi_timeline_vis/public/kibi_timeline_vis.less
    Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve module 'kibi-icons/lib/stylesheets/FontAwesomeKibi.css' in /data/ELK/kibana-4.5.0-linux-x64/installedPlugins/kibi_timeline_vis/public
        at Compilation.<anonymous> (/data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/lib/Compilation.js:228:38)
        at NormalModuleFactory.onDoneResolving (/data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/lib/NormalModuleFactory.js:28:20)
        at NormalModuleFactory.<anonymous> (/data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/lib/NormalModuleFactory.js:83:20)
        at /data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/async/lib/async.js:726:13
        at /data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/async/lib/async.js:52:16
        at done (/data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/async/lib/async.js:241:17)
        at /data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/async/lib/async.js:44:16
        at /data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/async/lib/async.js:723:17
        at /data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/async/lib/async.js:167:37
        at /data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
        at onResolved (/data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
        at innerCallback (/data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
        at loggingCallbackWrapper (/data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
        at /data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
        at /data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
        at /data/ELK/kibana-4.5.0-linux-x64/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
     @ ../kibana-4.5.0-linux-x64/installedPlugins/kibi_timeline_vis/public/kibi_timeline_vis.js 5:2-61

    ERROR in ../kibana-4.5.0-linux-x64/installedPlugins/kibi_timeline_vis/public/webpackShims/vis.js
    Module not found: Error: Cannot resolve module 'bower_components/vis/dist/vis.min.css' in /data/ELK/kibana-4.5.0-linux-x64/installedPlugins/kibi_timeline_vis/public/webpackShims
     @ ../kibana-4.5.0-linux-x64/installedPlugins/kibi_timeline_vis/public/webpackShims/vis.js 1:0-48

    ERROR in ../kibana-4.5.0-linux-x64/installedPlugins/kibi_timeline_vis/public/webpackShims/vis.js
    Module not found: Error: Cannot resolve module 'bower_components/vis/dist/vis.min.js' in /data/ELK/kibana-4.5.0-linux-x64/installedPlugins/kibi_timeline_vis/public/webpackShims
     @ ../kibana-4.5.0-linux-x64/installedPlugins/kibi_timeline_vis/public/webpackShims/vis.js 2:17-64

```
Regards

**Comment by scampi** [comment]
For now the latest version [0.1.4](https://github.com/sirensolutions/kibi_timeline_vis/releases/tag/0.1.4) works with Kibana 4.4.3

Also you should install the plugin from the link above, not from the master zip.

**Comment by iHile** [comment]
Hi, how about 4.5? :)

**Comment by scampi** [comment]
@iHile we will release kibi 4.5.3 soon, timeline will be updated soon as well.
